/**
 * PHASE 1 TEST: Hardcoded native elements
 *
 * This is NOT using OCR, decomposition, or any flattened images.
 * It's a plain DesignHub document with real native text and image elements.
 *
 * Purpose: Prove the editor can handle native text elements before fixing OCR.
 */

import { CanvasElement } from '../types';

export const testDesignFixture = {
  id: 'test-design-phase1',
  name: 'Phase 1 Test: Native Elements Only',
  canvasData: [{
    id: 'page-test-1',
    name: 'Page 1',
    width: 1024,
    height: 1536,
    backgroundColor: '#FFFFFF',
    elements: [
      // Background image
      {
        id: 'bg-image',
        type: 'image' as const,
        name: 'Background',
        x: 0,
        y: 0,
        width: 1024,
        height: 1536,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 0,
        data: {
          type: 'image' as const,
          src: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1024&h=1536&fit=crop',
          objectFit: 'cover' as const,
          borderRadius: 0,
          brightness: 100,
          contrast: 100,
          saturation: 100,
          hue: 0,
          blur: 0,
          filters: [],
          cropX: 0,
          cropY: 0,
          cropWidth: 100,
          cropHeight: 100,
        },
      },

      // Text element 1: HAPPY
      {
        id: 'text-happy',
        type: 'text' as const,
        name: 'HAPPY',
        x: 100,
        y: 200,
        width: 824,
        height: 120,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 10,
        data: {
          type: 'text' as const,
          content: 'HAPPY',
          fontFamily: 'Arial',
          fontSize: 96,
          fontWeight: 700,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#FFFFFF',
          lineHeight: 1.2,
          letterSpacing: 0,
          textTransform: 'none',
        },
      },

      // Text element 2: BIRTHDAY
      {
        id: 'text-birthday',
        type: 'text' as const,
        name: 'BIRTHDAY',
        x: 100,
        y: 350,
        width: 824,
        height: 140,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 10,
        data: {
          type: 'text' as const,
          content: 'BIRTHDAY',
          fontFamily: 'Arial',
          fontSize: 120,
          fontWeight: 700,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#FF6B9D',
          lineHeight: 1.2,
          letterSpacing: 2,
          textTransform: 'none',
        },
      },

      // Text element 3: DEAN SOET (small text)
      {
        id: 'text-dean',
        type: 'text' as const,
        name: 'DEAN SOET',
        x: 150,
        y: 600,
        width: 724,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 10,
        data: {
          type: 'text' as const,
          content: 'DEAN SOET',
          fontFamily: 'Arial',
          fontSize: 32,
          fontWeight: 400,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#333333',
          lineHeight: 1.2,
          letterSpacing: 0,
          textTransform: 'none',
        },
      },

      // Text element 4: Quote
      {
        id: 'text-quote',
        type: 'text' as const,
        name: 'Quote',
        x: 100,
        y: 700,
        width: 824,
        height: 100,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 10,
        data: {
          type: 'text' as const,
          content: 'Make a wish and blow out the candles!',
          fontFamily: 'Arial',
          fontSize: 28,
          fontWeight: 400,
          fontStyle: 'italic',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#666666',
          lineHeight: 1.5,
          letterSpacing: 0,
          textTransform: 'none',
        },
      },

      // Text element 5: Footer
      {
        id: 'text-footer',
        type: 'text' as const,
        name: 'Footer',
        x: 100,
        y: 1400,
        width: 824,
        height: 50,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 10,
        data: {
          type: 'text' as const,
          content: 'Celebrating you today!',
          fontFamily: 'Arial',
          fontSize: 24,
          fontWeight: 400,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#444444',
          lineHeight: 1.2,
          letterSpacing: 0,
          textTransform: 'none',
        },
      },

      // Image element: Party hat / decoration
      {
        id: 'img-decoration',
        type: 'image' as const,
        name: 'Party Decoration',
        x: 50,
        y: 150,
        width: 200,
        height: 200,
        rotation: -15,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 11,
        data: {
          type: 'image' as const,
          src: 'https://images.unsplash.com/photo-1513729784850-b7cecdc30dfe?w=200&h=200&fit=crop',
          objectFit: 'cover' as const,
          borderRadius: 0,
          brightness: 100,
          contrast: 100,
          saturation: 100,
          hue: 0,
          blur: 0,
          filters: [],
          cropX: 0,
          cropY: 0,
          cropWidth: 100,
          cropHeight: 100,
        },
      },

      // Image element: Balloon
      {
        id: 'img-balloon',
        type: 'image' as const,
        name: 'Balloon',
        x: 774,
        y: 150,
        width: 200,
        height: 200,
        rotation: 15,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 11,
        data: {
          type: 'image' as const,
          src: 'https://images.unsplash.com/photo-1549465220-94b4ba524314?w=200&h=200&fit=crop',
          objectFit: 'cover' as const,
          borderRadius: 0,
          brightness: 100,
          contrast: 100,
          saturation: 100,
          hue: 0,
          blur: 0,
          filters: [],
          cropX: 0,
          cropY: 0,
          cropWidth: 100,
          cropHeight: 100,
        },
      },
    ] as CanvasElement[],
  }],
};
